name: Build and Publish to GHCR

# Whenever code is pushed to the "main" branch, this Action (our automation worker) triggers automatically.
on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Borrow a free Ubuntu server provided by GitHub.
    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. Pull source code (Checkout)
        uses: actions/checkout@v4

      - name: 2. Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. Build Docker image and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest